# Generated by Django 3.2.6 on 2021-10-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('final', models.DateTimeField()),
                ('cancel', models.BooleanField(default=False)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='main.box')),
                ('oferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='main.oferente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('cancel', models.BooleanField(default=False)),
                ('confirmate', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('demandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita', to='main.demandante')),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita', to='agenda.disponibilidad')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita', to='main.servicio')),
            ],
            options={
                'ordering': ('-inicio',),
            },
        ),
    ]
