# Generated by Django 3.2.6 on 2021-10-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fono', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('adicional', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oferente', to='main.contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('agendable', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='main.area')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='main.pagina')),
            ],
            options={
                'unique_together': {('pagina', 'rut')},
                'index_together': {('pagina', 'rut')},
            },
        ),
        migrations.CreateModel(
            name='OferenteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='main.oferente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferentes', to='main.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='OferenteCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferentes', to='main.centro')),
                ('oferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros', to='main.oferente')),
            ],
        ),
        migrations.AddField(
            model_name='oferente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oferente', to='main.persona'),
        ),
        migrations.CreateModel(
            name='Demandante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demandante', to='main.contacto')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demandante', to='main.persona')),
            ],
        ),
        migrations.CreateModel(
            name='CentroServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='main.centro')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros', to='main.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='centro',
            name='contacto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='centro', to='main.contacto'),
        ),
        migrations.AddField(
            model_name='centro',
            name='direccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='centro', to='main.direccion'),
        ),
        migrations.AddField(
            model_name='centro',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros', to='main.pagina'),
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxs', to='main.centro')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='main.pagina'),
        ),
        migrations.CreateModel(
            name='UserPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.pagina')),
            ],
            options={
                'unique_together': {('pagina', 'email')},
                'index_together': {('pagina', 'email')},
            },
        ),
    ]
