# Generated by Django 3.2.6 on 2021-11-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
