# Generated by Django 3.2.6 on 2021-11-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pagina_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='extra_action_info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
