# Generated by Django 3.2.6 on 2021-10-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TextCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_card', to='content.container')),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_card', to='content.container')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seccion', to='main.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='MainCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_card', to='content.container')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='content.seccion'),
        ),
    ]
