# Generated by Django 3.2.6 on 2021-10-22 21:07

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincard',
            name='imagen',
            field=models.ImageField(default=1, upload_to=content.models.scramble_uploaded_filename),
            preserve_default=False,
        ),
    ]
