# Generated by Django 3.2.6 on 2021-10-22 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_maincard_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincard',
            old_name='imagen',
            new_name='imagen_titulo',
        ),
    ]
