# Generated by Django 3.2.6 on 2021-10-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_imagen_maincard_imagen_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincard',
            name='subtitulo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
