# Generated by Django 3.2.6 on 2021-10-25 05:41

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_maincard_parrafo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincard',
            name='imagen_main',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.scramble_uploaded_filename),
        ),
    ]
