# Generated by Django 3.2.6 on 2021-10-26 18:25

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_maincard_imagen_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarycard',
            name='imagen_main',
            field=models.ImageField(blank=True, null=True, upload_to=content.models.scramble_uploaded_filename),
        ),
        migrations.AddField(
            model_name='secondarycard',
            name='parrafo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
