# Generated by Django 3.2.6 on 2021-10-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20211026_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textcard',
            name='titulo',
        ),
        migrations.AddField(
            model_name='textcard',
            name='parrafo1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textcard',
            name='parrafo2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textcard',
            name='parrafo3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textcard',
            name='titulo1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textcard',
            name='titulo2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textcard',
            name='titulo3',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textcard',
            name='titulo_main',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
