# Generated by Django 3.2.6 on 2021-10-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20211027_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcard',
            name='titulo_main',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
