# Generated by Django 3.2.6 on 2021-10-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_textcard_titulo_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('parrafo', models.TextField()),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_card', to='content.container')),
            ],
        ),
    ]
