# Generated by Django 3.2.6 on 2021-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_actioncard'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
