# Generated by Django 3.2.6 on 2021-10-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_container_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ('position',)},
        ),
    ]
